### ISSUE TITLE
Columns in IS NULL expressions need to be stripped of optional quotes

### ISSUE THREAD

**Issue by jfengel** [vincentrussell/sql-to-mongo-db-query-converter#11]
A query like `"FOO" IS NULL` will be translated as `{"\"FOO\"": {$exists : false}}`. 
There is already a function, `getStringValue`, used to translate other column names. It should be used on line 432 as well, instead of `toString()`.

**Comment by vincentrussell** [comment]
fix with commit ceefec8d4fa9fd476d48bb9d6d305ddce34c2c97
