### ISSUE TITLE
-ve value of attribute Not supported if Type is int, long, etc.

### ISSUE THREAD

**Issue by anujwalia** [vincentrussell/sql-to-mongo-db-query-converter#14]
Example Query - 'Select * from X where Y=-1057614563' 
This query will fail with exception 'Can not parseNaturalLanguageDate'

**Comment by anujwalia** [comment]
I have fixed the issue, i can create a branch and push the changes and open PR, if you can grant me access.

**Comment by vincentrussell** [comment]
you can just do a pull request, but I believe what you want can be achieved by setting the FieldType for "Y" to be a NUMBER

**Comment by anujwalia** [comment]
so basically what happens is that if i pass a negative value in Y (int or Long), it takes a Signed Expression in the code and hence gets caught in the exception 'parseNaturalLanguageDate'.

**Comment by vincentrussell** [comment]
ok.  please create a fork and submit a pull request.

**Comment by anujwalia** [comment]
done

**Comment by vincentrussell** [comment]
I don't see a pull request.  Can you just copy and paste your diff or something?

**Comment by vincentrussell** [comment]
OK.. i just commited 10a74b3c2d1049b2f4549cd17dda715b5897bb92 based on your description.  This should fix your issue.   Let me know if you need a release.

Thanks,
