### ISSUE TITLE
strict mode

### ISSUE THREAD

**Issue by webpq** [vincentrussell/sql-to-mongo-db-query-converter#16]
the mongo statement is under strict mode,so it cannot work in the mongo shell

**Comment by vincentrussell** [comment]
What mongo statement?

**Comment by webpq** [comment]
> What mongo statement?

eg:
the sql statement:  SELECT * FROM test WHERE age=4
converted mongo statement: db.test.find({
                                                  "age": {
                                                     "$numberLong": "4"
                                                   }
                                                 })

the mongo statement cannot directly work in mongo shell,because the "$numberLong" cannot be recognized.

**Comment by vincentrussell** [comment]
I wrote the following test so I am not seeing the conversion of 4 to $numberLong:

    @Test
    public void queryLong() throws ParseException {
        QueryConverter queryConverter = new QueryConverter("select * from my_table WHERE age=4");
        MongoDBQueryHolder mongoDBQueryHolder = queryConverter.getMongoQuery();
        assertEquals(0,mongoDBQueryHolder.getProjection().size());
        assertEquals("my_table",mongoDBQueryHolder.getCollection());
        assertEquals(document("age",4L),mongoDBQueryHolder.getQuery());
    }
