### ISSUE TITLE
Can I convert sql query to mongodb for array of objects using $elementMatch?

### ISSUE THREAD

**Issue by rajputvijay32** [vincentrussell/sql-to-mongo-db-query-converter#17]
I want to use $elementMatch in my mongodb query and my document structure is - 

    "itineraries": {
            "travelers": [
                {
                    "travelerName": {
                        "givenName": "Captain",
                        "surname": "Obvious"
                    }
                },
                {
                    "travelerName": {
                        "givenName": "Peter",
                        "surname": "Ngunyi"
                    }
                }
            ]
        }

I want sql equivalent query of db.collection.find({"itineraries.travelers" : {"$elementMatch" : {"travelerName.givenName" : "Captain", "travelerName.surname" : "Obvious"}}}. Can I write or convert a SQL query to this given mongodb query?

**Comment by vincentrussell** [comment]
No.  Not currently.  What would the SQL syntax look like?
