### ISSUE TITLE
Sql contains group by column order by count(*) desc limit 3, execute error in mongodb.

### ISSUE THREAD

**Issue by javalover123** [vincentrussell/sql-to-mongo-db-query-converter#20]
"errmsg" : "the limit must be specified as a number", modify {"$numberLong": "3"} to 3, then is ok.
select aaa, count(*) from tttt group by aaa order by count(*) desc limit 3;
db.tttt.aggregate([{
  "$match": {}
},{
  "$group": {
    "_id": "$aaa",
    "count": {
      "$sum": 1
    }
  }
},{
  "$sort": {
    "count": -1
  }
},{
  "$limit": {
    "$numberLong": "3"
  }
}])

**Comment by vincentrussell** [comment]
This query should work now with the latest version.
