### ISSUE TITLE
Get only Mongo's native query

### ISSUE THREAD

**Issue by ronnypeterson** [vincentrussell/sql-to-mongo-db-query-converter#21]
Hi,

I would like to insert sql and get only Mongo's native query. I used this code, but it didn't work:

```
                QueryConverter queryConverter;
		try 
		{
			queryConverter = new QueryConverter(sql);
			queryConverter = new QueryConverter("select column1 from my_table where value NOT IN ('theValue1','theValue2','theValue3')");
			MongoDBQueryHolder mongoDBQueryHolder = queryConverter.getMongoQuery();
			String collection = mongoDBQueryHolder.getCollection();
			Document query = mongoDBQueryHolder.getQuery();
			Document projection = mongoDBQueryHolder.getProjection();
			Document sort = mongoDBQueryHolder.getSort();			
			System.out.println(queryConverter.getMongoQuery());			
			return queryConverter.getMongoQuery().toString();
		} 
		catch (ParseException e) 
		{
			// TODO Auto-generated catch block
			result = e.toString();
			return result;
		}
```

What to print to see Mongo's query?

Thanks,

Ronny

**Comment by ronnypeterson** [comment]
I did it! Not sure if it's the best solution, but it worked:

``public static String parser(String sql) throws Exception
	{	
		OutputStream outputStream = null;		
		QueryConverter queryConverter;
		try 
		{	            
            outputStream = new ByteArrayOutputStream();
            queryConverter = new QueryConverter(sql);
			queryConverter.write(outputStream);
			
			return outputStream.toString();
		} 
		catch (Exception e) 
		{
			throw new Exception(e.toString());
		}
    }``

Thanks!

**Comment by vincentrussell** [comment]
sorry for the delayed reply.  I'm glad that you figured it out.
