### ISSUE TITLE
Conjunctions with a function throw an exception

### ISSUE THREAD

**Issue by jfengel** [vincentrussell/sql-to-mongo-db-query-converter#3]
Try the call:

`new QueryConverter("select * from table where QUICKSEARCH('123') AND (foo = 'bar')", FieldType.STRING)`

The exception I get is:

can not parseNaturalLanguageDate: QUICKSEARCH('123')

I think the fix may be on line 443:
` query.put("$and", Arrays.asList(parseExpression(new Document(), leftExpression, rightExpression), parseExpression(new Document(), rightExpression, leftExpression)));`
should perhaps be:
` query.put("$and", Arrays.asList(parseExpression(new Document(), leftExpression, null), parseExpression(new Document(), rightExpression, null)));`

**Comment by vincentrussell** [comment]
Josh,

I made the following change:

diff --git a/src/main/java/com/github/vincentrussell/query/mongodb/sql/converter/QueryConverter.java b/src/main/java/com/github/vincentrussell/query/mongodb/sql/converter/QueryConverter.java
index b799686..6624ba7 100644
--- a/src/main/java/com/github/vincentrussell/query/mongodb/sql/converter/QueryConverter.java
+++ b/src/main/java/com/github/vincentrussell/query/mongodb/sql/converter/QueryConverter.java
@@ -484,6 +484,8 @@ public class QueryConverter {
             return normalizeValue((((StringValue)incomingExpression).getValue()),fieldType);
         } else if (Column.class.isInstance(incomingExpression)) {
             return normalizeValue(getStringValue(incomingExpression),fieldType);
+        } else if (Function.class.isInstance(incomingExpression)) {
+            return normalizeValue(getStringValue(incomingExpression),fieldType);
         } else {
             throw new ParseException("can not parseNaturalLanguageDate: " + incomingExpression.toString());
         }


What do you expect the resulting json to look like?  With this fix I just did I get:

{ "$and" : ["QUICKSEARCH('123')", { "foo" : "bar" }] }

This seems like it would be difficult to parse.

**Comment by jfengel** [comment]
I believe that's the result I'm expecting.

**Comment by vincentrussell** [comment]
ok.. i think it should be turned into:

{ "$and" : [{"$QUICKSEARCH":['123']}, { "foo" : "bar" }] }

this would make it much easier to parse from the client-code perspective.  this would give the ability to potentially pass down mongo functions in the sql format.

**Comment by jfengel** [comment]
That would work, especially since that form does support multiple arguments. Potentially it could support fairly complicated structures.

Currently my code just looks for the special case of a value beginning with QUICKSEARCH(', which is clunky but it does function.

**Comment by vincentrussell** [comment]
ok.. check this out.

https://github.com/vincentrussell/sql-to-mongo-db-query-converter/commit/6a9d8a469947c642a6bed808974aa9021cd10fa3

**Comment by vincentrussell** [comment]
I'll push a new release this weekend.
