### ISSUE TITLE
Maven POM - Version 1.10 - Error in compiling

### ISSUE THREAD

**Issue by GitJayKay** [vincentrussell/sql-to-mongo-db-query-converter#33]
Greetings.
Thanks for this super project. When tried to use this by adding the POM on Ver 1.10 - The following error is thrown: "**QueryConverter.Builder cannot be resolved to a type**"

When I looked in to the JAR file - QueryConverter class does not have the static class "Builder". Can you please help on this. I can go for separate JAR file in the library - I don't want that approach. 

Thanks.

**Comment by vincentrussell** [comment]
Sorry for the confusion.   The builder is in version 1.11 which hasn't been released yet.  I was awaiting to gather more features to release 1.11

**Comment by vincentrussell** [comment]
Please look at the tests to see how to initiate the querybuilder.  I might release it today. It's been a while

**Comment by vincentrussell** [comment]
I just released version 1.11.   Hopefully it will be in maven central soon.

**Comment by GitJayKay** [comment]
Awesome. Thanks a lot.

**Comment by GitJayKay** [comment]
Hello Vincent.
I got the 1.11 version and it is working great. Thanks again.
