### ISSUE TITLE
Exception when we have multiple NOT statements

### ISSUE THREAD

**Issue by HoomanT** [vincentrussell/sql-to-mongo-db-query-converter#34]
HI
When I use multiple NOT statements in the input, it throws an exception. example:
```
SELECT * FROM Customers
WHERE NOT (Country='Germany' AND City='Berlin') and NOT (Country='Mexico');
```
I can rewrite my query to solve this problem, but I just wanted to report this issue.
Thanks

**Comment by vincentrussell** [comment]
Does the code from this commit look right?  5af530789fe01dbc84c2bc903a6d549a49db288a
