### ISSUE TITLE
NOT LIKE Operator

### ISSUE THREAD

**Issue by HoomanT** [vincentrussell/sql-to-mongo-db-query-converter#35]
I also found that I can't use NOT LIKE operator.
Can you add support for this command?

**Comment by vincentrussell** [comment]
It looks like 550d79b85cf78ead5023c7969cc41b3a34dfa122 resolves this.  I thought this wasn't possible at first.

**Comment by HoomanT** [comment]
By the way, I also found that we can't use column names like 3rd_column in our SQL commands, meaning column names that their first letter is a number. As you know, we use [3rd_column] as a workaround for this problem, but it is not possible now and gives an exception after seeing '[' in our column names. I posted this issue here as a comment and didn't open a new Issue.
And would you commit your new changes to maven so I can check it faster against my test cases inside my program. Thanks

**Comment by vincentrussell** [comment]
I am not sure I understand your issue.  Can you provide a sample query.

Also, you should be able to build on your own and test with a snapshot, right?

**Comment by HoomanT** [comment]
OK here's an example. I Have a query like this:
SELECT * FROM tb_test WHERE [3rd_column] = 10
this is what I get:
```
com.github.vincentrussell.query.mongodb.sql.converter.ParseException: Encountered unexpected token: "[" "["
    at line 1, column 24.

Was expecting one of:

    "!"
    "("
    "NOT"

	at com.github.vincentrussell.query.mongodb.sql.converter.util.SqlUtils.convertParseException(SqlUtils.java:287)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter.<init>(QueryConverter.java:182)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter$Builder.build(QueryConverter.java:841)
	....
```

**Comment by vincentrussell** [comment]
That's not valid SQL.  It isn't making it through the SQL parser phase.

**Comment by HoomanT** [comment]
So how do you handle column names that the first letter of their name is a number, like the example above?
I used [3rd_column] because some SQL databases accept it, in some cases we should use "3rd_column".
If I enter the command like this:
`select * from tb where 3rd_column = 10 `
I will get this exception:
```
com.github.vincentrussell.query.mongodb.sql.converter.ParseException: Encountered unexpected token: "rd_column" <S_IDENTIFIER>
    at line 1, column 25.

Was expecting one of:

    "&"
    "&&"
    "::"
    ";"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "ORDER"
    "START"
    "UNION"
    "["
    "^"
    "|"
    <EOF>

	at com.github.vincentrussell.query.mongodb.sql.converter.util.SqlUtils.convertParseException(SqlUtils.java:287)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter.<init>(QueryConverter.java:182)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter$Builder.build(QueryConverter.java:841)
```

**Comment by vincentrussell** [comment]
I use a library called jsqlparser to parse the sql.  It looks like it doesn't support having columns that begin with numbers.

By the way.  I just release version 1.13.

**Comment by vincentrussell** [comment]
I was playing around with this to try and figure this out and I found out that you can use numbers in your column names if you surrond them in quotes.

SELECT * FROM tb_test WHERE "3rd_column" = 10

**Comment by HoomanT** [comment]
> I use a library called jsqlparser to parse the sql. It looks like it doesn't support having columns that begin with numbers.
> 
> By the way. I just release version 1.13.

Thanks For New Release

**Comment by HoomanT** [comment]
> I was playing around with this to try and figure this out and I found out that you can use numbers in your column names if you surrond them in quotes.
> 
> SELECT * FROM tb_test WHERE "3rd_column" = 10

Sorry for the late reply. I will play around and see if it works fine.
by the way, I have a query like this:

`select * from tb where avg = 1.5`

but it gave me this exception
```
com.github.vincentrussell.query.mongodb.sql.converter.ParseException: can not parseNaturalLanguageDate: 1.0
	at com.github.vincentrussell.query.mongodb.sql.converter.util.SqlUtils.getValue(SqlUtils.java:84)
        .....
```
I found out that it is because my value is not an integer. Is there some special way to treat float or double values?

**Comment by vincentrussell** [comment]
definitely I bug... i fixed this under https://github.com/vincentrussell/sql-to-mongo-db-query-converter/commit/ad6da05ff872a232d4ba9f079136b356d0a9a254  and released this as v1.14

**Comment by HoomanT** [comment]
when using signed numbers in conditions, the result will be converted into string for example:
`select column from my_table where value = -10`
or
`select column from my_table where value = +3.5`
and the query part of the output will be:
`{"value":"-10"}`
and
`{"value":"+3.5"}`
which is a wrong behavior.

**Comment by HoomanT** [comment]
> I was playing around with this to try and figure this out and I found out that you can use numbers in your column names if you surrond them in quotes.
> 
> SELECT * FROM tb_test WHERE "3rd_column" = 10

I tested this method and it has a missing $ before the column name for exmaple:
`SELECT * FROM tb_test WHERE "3rd_column" = 10`
the query part of the output will be:
`{"$expr": {"$eq": ["3rd_column", {"$numberLong": "10"}]}}`
which is wrong and must have a $ before the column name, resulting:
`{"$expr": {"$eq": ["$3rd_column", {"$numberLong": "10"}]}}`

**Comment by vincentrussell** [comment]
Can you please open up new github issues for different issues.  This thread is going on too long.

**Comment by HoomanT** [comment]
> Can you please open up new github issues for different issues. This thread is going on too long.

OK. if found any other issues, I will open them as a new thread
