### ISSUE TITLE
Subqueries not working

### ISSUE THREAD

**Issue by raghavrammohan** [vincentrussell/sql-to-mongo-db-query-converter#36]
I tried the below query and couldn't generate the equivalent mongo query
select * from employees where name in (select name from exp)

Does the current version support sub queries? If yes, can you add an example for the subqueries case in the readme so that it will be useful

**Comment by vincentrussell** [comment]
Some subqueries are supported, like this: (select c.cuisine, c.c as c  from(select borough, cuisine, count(*) as c from Restaurants group by borough, cuisine limit 6000) as c where c.cuisine = 'Hamburgers' and c.borough ='Manhattan') and some aren't.  

It looks like this one is not.  What would you expect the mongo aggregation to look like based on this query and perhaps I could make this work.
