### ISSUE TITLE
How to get Groupby Document

### ISSUE THREAD

**Issue by karth06** [vincentrussell/sql-to-mongo-db-query-converter#39]
Hi,
How can i get group by document in json format using java code.
For example if i do mongoDBQueryHolder.getProjection(), i get the projection document which i can later see in json format
I cant find the same with group by clause.

Thank you

**Comment by vincentrussell** [comment]
I'm not sure if the library provides what you want or if you want really makes sense, but I may not be understanding you.

You can call mongoDBQueryHolder.getGroupBys(), but that will just give you a list.

If you call queryConverter.write(), that will write all of the mongo code necessary for the group by.  for instance:

SELECT agent_code,   
COUNT (*)   
FROM orders 
 WHERE agent_code LIKE 'AW_%'
GROUP BY agent_code;

converts to the following string via the write method:


db.orders.aggregate([{
  "$match": {
    "agent_code": {
      "$regex": "^AW.{1}.*$"
    }
  }
},{
  "$group": {
    "_id": "$agent_code",
    "count": {
      "$sum": 1
    }
  }
},{
  "$project": {
    "agent_code": "$_id",
    "count": 1,
    "_id": 0
  }
}])

**Comment by karth06** [comment]
queryConverter.write() takes outputstream as parameters.
how can i store this in an java variable and pass it on to the collection so that i can filter out the results
can you please show an example

**Comment by karth06** [comment]
i want to store the following output
String outputString=db.orders.aggregate([{
"$match": {
"agent_code": {
"$regex": "^AW.{1}.*$"
}
}
},{
"$group": {
"_id": "$agent_code",
"count": {
"$sum": 1
}
}
},{
"$project": {
"agent_code": "$_id",
"count": 1,
"_id": 0
}
}])

in an variable and then pass it on to a collection like
AggregateIterable<Document> document=Aggregatemongodatabase.aggregate(outputString)'
and then i filterout the result for further processing, is there a way where how can i achieve this

**Comment by vincentrussell** [comment]
What you want is not currently not possible, but I'll take it as a requirement.

**Comment by karth06** [comment]
okay, thank you

**Comment by vincentrussell** [comment]
Ok... i see the folllowing commit:  7a6931b818a520d1ad0309bbaa2c6cd66a8ddd9a

I'll merge it later today.

**Comment by vincentrussell** [comment]
I'll release it later today I mean.

**Comment by karth06** [comment]
Thank you so much again.
