### ISSUE TITLE
Mongo Query Executer

### ISSUE THREAD

**Issue by karth06** [vincentrussell/sql-to-mongo-db-query-converter#43]
Any particular java method which can take sql query as input and give me the result from mongo? like for example the following command
java -jar target/sql-to-mongo-db-query-converter-1.18-SNAPSHOT-standalone.jar -i -h localhost:3086 -db local -b 5

select borough, cuisine, count(*) from my_collection GROUP BY borough, cuisine ORDER BY count(*) DESC;

Thanks and Regards
karthik

**Comment by vincentrussell** [comment]
I am not sure I understand your question, but I think you just want to remove the -i for interactive mode.

**Comment by karth06** [comment]
No No,
is there any java method where i can pass sql statement, and i get output of desired query.
For example:
**input**:
select borough, cuisine, count() from my_collection GROUP BY borough, cuisine ORDER BY count() DESC;

**output**:
******Query Results:*********

[{
	"borough" : "Manhattan",
	"cuisine" : "American ",
	"count" : 3205
},{
	"borough" : "Brooklyn",
	"cuisine" : "American ",
	"count" : 1273
},{
	"borough" : "Queens",
	"cuisine" : "American ",
	"count" : 1040
}


how can i do the same with help of java.

**Comment by vincentrussell** [comment]
Yes.  You can call the run method on the QueryConverter object and pass it a MongoDatabase object.

**Comment by karth06** [comment]
got it thank you,
one more thing sorry to bother you,can i execute mongo native queries also?
i will directly pass mongo native query instead of sql and it should return me the result.

**Comment by vincentrussell** [comment]
No.  The input needs to always be SQL.  That's the whole point of the library
