### ISSUE TITLE
Semantic issue with 'having' + an aggregator

### ISSUE THREAD

**Issue by m-bagley1020** [vincentrussell/sql-to-mongo-db-query-converter#49]
Hello,

Great package here. It's very impressive and can handle many use cases. I have found a small semantic. Take the following query:

```sql
select avg(rating) from untable having (rating < 40);
```

Output:

```json
[
  {
    "$group": {
      "_id": {},
      "avg_rating": {
        "$avg": "$rating"
      }
    }
  },
  {
    "$match": {
      "rating": {
        "$lt": {
          "$numberLong": "40"
        }
      }
    }
  },
  {
    "$project": {
      "avg_rating": 1,
      "_id": 0
    }
  }
]
```

In the `$group` field, the _rating_ column is mapped to _avg\_rating_, but then is referenced as _rating_ in the `$match` field. In order for this query to work properly, it needs to be referenced as _avg\_rating_.

Is there any possible fix to this? Thank you!

**Comment by vincentrussell** [comment]
I am not sure why I"ll be able to take a look at this.  Potentially this weekend, but I am not sure.   You are more than welcome to submit a pull request if you need it sooner.

**Comment by vincentrussell** [comment]
I pushed a fix.  Please let me know if it looks correct and I'll do a release.
