### ISSUE TITLE
Options not supported for like query however they do for not like

### ISSUE THREAD

**Issue by Sharadk007** [vincentrussell/sql-to-mongo-db-query-converter#52]
Hi,

Options to make like query case insensitive is not supported in current version, could you please update it, thanks.

**Comment by Sharadk007** [comment]
Hi 

I have added pattern compilation for like query as well

**Comment by vincentrussell** [comment]
This is supported.  There is a test that shows how to use it:

`    @Test
    public void regexMatchWithOptions() throws ParseException {
        QueryConverter queryConverter = new QueryConverter.Builder().sqlString("select * from my_table where regexMatch(column,'^[ae\"gaf]+$','si') = true ").build();
        MongoDBQueryHolder mongoDBQueryHolder = queryConverter.getMongoQuery();
        assertEquals(0,mongoDBQueryHolder.getProjection().size());
        assertEquals("my_table",mongoDBQueryHolder.getCollection());
        assertEquals(document("column",document("$regex","^[ae\"gaf]+$").append("$options","si")),mongoDBQueryHolder.getQuery());
    }`
