### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by Lewiscowles1986** [vincentrussell/sql-to-mongo-db-query-converter#55]
Hey there 👋 

Thanks so much for all your work on this. It helped me out yesterday with a `GROUP BY` query against MongoDB. I Had a rough idea of what to do (turns out I was missing projection group from reading your output. But it just wasn't working, and I didn't want to issue multiple queries.

I Built this twice yesterday. Once on my local, which was using Java 11. For that I removed the `com.github.spotbugs`. And then using GitHub via GitHub actions against Java 1.8, publishing the result of the build as an artifact.

I was wondering if you'd welcome a PR to add the GitHub actions work upstream?

**Comment by vincentrussell** [comment]
Hello,

I'm sorry for the delayed response.  This has been a busy week.  Sure... I welcome all PRs if they look good.   What is GitHub actions?  Sorry.  I am not sure I understand the changes you are proposing.

**Comment by Lewiscowles1986** [comment]
I Just raised the PR. Happy to squash the commits into one, discuss what might be a good move to have this in addition to or as alternative to Travis.
