### ISSUE TITLE
SQL safe words

### ISSUE THREAD

**Issue by dilan-dio4** [vincentrussell/sql-to-mongo-db-query-converter#57]
Hello. Thanks for this library. It's truly great. One issue thing I run into sometimes is unexpected SQL safe words that I should be checking for. This can cause issues like as follows:

```
Unexpected kw_user token: "user". Instead, I was expecting to see one of the following:

    - A "kw_primary" token
    - A "kw_unique" token
    - A "word" token
```

Is there a place where I could find a list of these safe words I should be checking for?

Thanks

**Comment by vincentrussell** [comment]
I am not sure I understand your question.  What query were you trying to run?

I am using a library called jsqlparser to actually parse the sql statements so I think that is what you are asking about.
