### ISSUE TITLE
NullPointerException when using sql joins 

### ISSUE THREAD

**Issue by nourferhane** [vincentrussell/sql-to-mongo-db-query-converter#58]
hello, thank you so muuch for this lib <3 
i have an issue when using query with Join , can you check that please ? :)

**Comment by vincentrussell** [comment]
This is not enough information to help you.  What query are you running?

**Comment by nourferhane** [comment]
hello Sir ,
sorry my mistak :3  i just saw there is a forgotten ON 
thank you
