### ISSUE TITLE
where with in not working having inner join

### ISSUE THREAD

**Issue by beuwolf-u** [vincentrussell/sql-to-mongo-db-query-converter#59]
Hello, i did the follow query and the result didn't do the filtering

select t1.type from attributes as t1 inner join status as t2 on t1.status = t2.id where t1.type in ( 'USER', 'PARKING')

here the object doesn't have the match
![image](https://user-images.githubusercontent.com/59735140/143106955-21a53a72-909f-4efd-bd4f-2d78fb7deeb9.png)

but doing it without a in, it worked

select t1.type from attributes as t1 inner join status as t2 on t1.status = t2.id where t1.type = 'USER'

the object here does have the match
![image](https://user-images.githubusercontent.com/59735140/143106651-f3887766-4728-4add-a01a-4eb94da53217.png)

**Comment by vincentrussell** [comment]
sorry.. i'll try to look at this soon.   thanks for reporting

**Comment by vincentrussell** [comment]
I didn't write a lot of this code so I'll do my best to figure out what's going on.

**Comment by vincentrussell** [comment]
I committed the following code: 89168dacb292a79c411a49ad92407a4cffa0ab07

Would you mind building the version that's on the master branch and letting me know if that solves your issue?

**Comment by beuwolf-u** [comment]
yes sir! looks like it works :D

**Comment by vincentrussell** [comment]
ok.  I'll try to cut v1.19 tomorrow.
