### ISSUE TITLE
Bug with dates 

### ISSUE THREAD

**Issue by francescolarocca** [vincentrussell/sql-to-mongo-db-query-converter#60]
Hi, I'm trying to convert this query: 

`select * from XXXX where space = "1-h" and country = "ita" and domain ="topology" and date(valid_to,'YYYY-MM-DD') >= '2099-12-31'`

following the readme file

![image](https://user-images.githubusercontent.com/59647790/143282862-47e8bfa4-4448-45d2-bbf3-cdab81e63fa8.png)

the library convert my previuous query right this: 

![image](https://user-images.githubusercontent.com/59647790/143283318-8bd2818c-45e7-4f8f-9905-726b8940c2cf.png)

I tried also the pattern in the readme file 'yyy' instead of 'yyyy' but does not work neither, the date is incorrect.

**Comment by vincentrussell** [comment]
sorry.. i'll try to look at this soon.   thanks for reporting

**Comment by beuwolf-u** [comment]
same happen to me, try with 'yyyy-MM-dd' this is something not related with vincentrussell library

**Comment by vincentrussell** [comment]
The documentation is incorrect.  The pattern for year should be YYYY.

However;  I don't think this is a bug.  I think you are looking at how to toString for the Date object is formatted on your machine


This should tell you how mongo would interpret the json:
mongoDBQueryHolder.getQuery().toJson(JsonWriterSettings.builder().outputMode(JsonMode.SHELL).build()))


on my machine that query turns into:
{"$and": [{"space": "1-h"}, {"country": "ita"}, {"domain": "topology"}, {"valid_to": {"$gte": ISODate("2099-01-31T00:00:00.000Z")}}]}
